Repository cagov/caldata-mdsa-caltrans-pems, pull requests merged in 2024-10, with the labels that each got.

#402 Smooth Speed Calculation
  transform/dbt_project.yml
  transform/models/intermediate/clearinghouse/_clearinghouse.yml
  transform/models/intermediate/clearinghouse/int_clearinghouse__detector_g_factor_based_speed.sql
Labels: p0 - Immediate need

#419 Ten days corridor level performance mart model bug fixing
  transform/models/marts/performance/_performance.yml
  transform/models/marts/performance/performance__station_metric_agg_recent_one_week.sql
Labels: bug, p1 - High priority

#433 Included county and lat-long in aadt model
  transform/models/marts/performance/_performance.yml
  transform/models/marts/performance/performance__station_aadt_k_value.sql
Labels: p2 - Med priority

#434 create a copy of imputed 5 mins data to mart for visualization purpose
  transform/models/marts/imputation/_imputation.yml
  transform/models/marts/imputation/imputation__detector_imputed_agg_five_minutes.sql
Labels: p2 - Med priority

#443 created the macro function to replace all county code with county nam…
  poetry.lock
  pyproject.toml
  transform/macros/_macros.yml
  transform/macros/get_county_name.sql
  transform/models/marts/diagnostics/diagnostics__detector_daily_by_station.sql
  transform/models/marts/diagnostics/diagnostics__detector_daily_detail.sql
  transform/models/marts/diagnostics/diagnostics__detector_monthly_by_station.sql
  transform/models/marts/geo/geo__current_detectors.sql
  transform/models/marts/imputation/imputation__detector_imputed_agg_five_minutes.sql
  transform/models/marts/performance/performance__agg_yearly_county.sql
  transform/models/marts/performance/performance__station_aadt_k_value.sql
  transform/models/marts/performance/performance__station_metric_agg_recent_one_week.sql
  transform/models/marts/performance/performance__station_metrics_agg_daily.sql
  transform/models/marts/performance/performance__station_metrics_agg_monthly.sql
Labels: p1 - High priority

#447 there was error in formula. Fixed the bugs
  transform/models/marts/performance/performance__station_metric_agg_recent_one_week.sql
Labels: p0 - Immediate need

#449 Fix the duplicate rows bug in aadt model
  transform/models/intermediate/performance/int_performance__station_aadt_with_K_value.sql
Labels: p2 - Med priority

#452 replace the valid_from with active_date to have recent meta data for PERFORMANCE__STATION_METRIC_AGG_RECENT_ONE_WEEK model
  transform/models/marts/performance/performance__station_metric_agg_recent_one_week.sql
Labels: bug
